some-secret: ${sm://SOME_SECRET}

spring:
  cloud:
    gcp:
      project-id: ${PROJECT_ID}
      secretmanager:
        enabled: true
        project-id: ${PROJECT_ID}

logging:
  level:
    com.google: DEBUG
